<script setup>
import { Head, Link, router } from '@inertiajs/vue3';
import DirectoryListingForm from '../../../Components/DirectoryListingForm.vue';
import PlatformLayout from '../../../Layouts/PlatformLayout.vue';
const props = defineProps({ listing: Object, sports: Array, sourceTypes: Array, weekdays: Array, locationParents: Array });
function action(name) {
    let payload = {};
    if (name === 'verify') { const verification_notes = window.prompt('What did you check, and where did you check it?'); if (!verification_notes) return; payload = { verification_notes }; }
    if (name === 'close' || name === 'remove') { const reason = window.prompt(`Why should this venue be marked ${name === 'close' ? 'closed' : 'hidden'}?`); if (!reason) return; payload = { reason }; }
    router.post(`/platform/directory/${props.listing.slug}/${name}`, payload, { preserveScroll: true });
}
function claimedVenueAction(name) {
    const promptText = name === 'verify-claimed-venue'
        ? 'Describe the completed marketplace review, including the venue details and active court you checked:'
        : 'Explain the ownership dispute or safety reason for removing marketplace access:';
    const value = window.prompt(promptText);
    if (!value) return;
    const payload = name === 'verify-claimed-venue' ? { verification_notes: value } : { reason: value };
    router.post(`/platform/directory/${props.listing.slug}/${name}`, payload, { preserveScroll: true });
}
</script>
<template><Head :title="`Edit ${listing.name}`" /><PlatformLayout><div class="mx-auto max-w-5xl"><Link href="/platform/directory" class="text-sm font-semibold text-court-700">← Public venue guide</Link><div class="my-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">Venue details</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">{{ listing.name }}</h1><p class="mt-2 text-sm text-slate-500">{{ listing.status_label }} · Last checked {{ listing.last_verified_at || 'never' }}</p></div><div class="flex flex-wrap gap-2"><a :href="`/directory/${listing.slug}`" target="_blank" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">View public page ↗</a><button v-if="!['claimed','removed'].includes(listing.status)" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold" @click="action('verify')">Mark details checked</button><button v-if="listing.status !== 'published' && !['claimed','removed'].includes(listing.status)" class="rounded-xl bg-court-700 px-4 py-2.5 text-sm font-semibold text-white" @click="action('publish')">Show publicly</button><button v-if="listing.status === 'published'" class="rounded-xl border border-amber-200 px-4 py-2.5 text-sm font-semibold text-amber-800" @click="action('close')">Mark as closed</button><button v-if="!['claimed','removed'].includes(listing.status)" class="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-semibold text-red-700" @click="action('remove')">Hide from guide</button></div></div>
<section v-if="listing.claimed_venue" class="app-card mb-7 p-6"><div class="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p class="eyebrow">Second safety gate</p><h2 class="mt-2 text-xl font-semibold">Marketplace review for {{ listing.claimed_venue.name }}</h2><p class="mt-2 text-sm leading-6 text-slate-600">Owned by {{ listing.claimed_venue.organization }}. Ownership approval only created private access; it did not authorize public bookings.</p><div class="mt-4 flex flex-wrap gap-2 text-xs font-semibold"><span class="rounded-full bg-slate-100 px-3 py-1.5">{{ listing.claimed_venue.is_published ? 'Owner requested publication' : 'Owner still preparing' }}</span><span class="rounded-full bg-slate-100 px-3 py-1.5">{{ listing.claimed_venue.active_resources_count }} active courts</span><span :class="['rounded-full px-3 py-1.5', listing.claimed_venue.is_marketplace_verified ? 'bg-court-50 text-court-800' : 'bg-amber-50 text-amber-800']">{{ listing.claimed_venue.is_marketplace_verified ? 'Marketplace approved' : 'Marketplace blocked' }}</span></div></div><div class="flex flex-wrap gap-2"><button v-if="!listing.claimed_venue.is_marketplace_verified" class="rounded-xl bg-court-700 px-4 py-2.5 text-sm font-semibold text-white" @click="claimedVenueAction('verify-claimed-venue')">Complete marketplace review</button><button v-else class="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-semibold text-red-700" @click="claimedVenueAction('revoke-claimed-venue')">Remove marketplace access</button></div></div><p class="mt-4 rounded-xl bg-amber-50 p-4 text-xs leading-5 text-amber-900">Before approval, confirm the ownership-proof audit, venue identity, contact details, active court, pricing, and publication request. A dispute removes verification and unpublishes the venue immediately.</p></section>
<DirectoryListingForm v-if="listing.status !== 'claimed'" :listing="listing" :sports="sports" :source-types="sourceTypes" :weekdays="weekdays" :location-parents="locationParents" /><section class="app-card mt-7 p-6"><h2 class="text-lg font-semibold">Change history</h2><p class="mt-1 text-sm text-slate-500">A simple record of who changed this venue and when.</p><div class="mt-4 divide-y divide-slate-100"><div v-for="audit in listing.audits" :key="`${audit.event_type}-${audit.occurred_at}`" class="py-3"><div class="flex justify-between gap-4 text-sm"><strong>{{ audit.event_type }}</strong><span class="text-slate-400">{{ audit.occurred_at }}</span></div><p class="mt-1 text-xs text-slate-500">{{ audit.actor }}</p></div></div></section></div></PlatformLayout></template>
